#!/usr/bin/env python3
"""Rebuild index.md in a notes folder: a nested outline of its notes by topic.

Usage: build-index.py <notes dir>

Research notes go under `## <area>`, and `### <sub-area>` if their `topic` has one. Idea and
decision notes are sub-items of the first research note in their `related` that exists; a
`~/notes/...` entry is read relative to <notes dir>, so a scratch copy resolves against itself.
A research note with no usable topic, and an idea or decision naming no research note, go
under `## Unfiled`. Dotfiles, such as the agent evals' hidden notes, are left out.

Markmap shows the file as a mind map, and any markdown viewer as a list. The whole file is
rebuilt from disk each time, and everything is sorted, so the same notes give the same bytes.
Prints the path and counts of topics, notes and unfiled notes.
"""

import sys
from collections import defaultdict
from pathlib import Path
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mdcheck import (
    TOPIC,
    flow_list,
    frontmatter,
)

USAGE = "usage: build-index.py <notes dir>"
KINDS = ("research", "ideas", "decisions")
HEADER = """---
title: Notes index
markmap:
  initialExpandLevel: 2
---

<!-- Generated by ~/.claude/skills/research/scripts/build-index.py from each note's topic. \
Don't edit by hand. -->

# Notes
"""


def notes(root, kind):
    """(path relative to root, frontmatter) for each note of this kind, sorted by filename."""
    return [
        (
            path.relative_to(root).as_posix(),
            frontmatter(path.read_text(errors="replace").splitlines())[0],
        )
        for path in sorted((root / kind).glob("*.md"))
        if not path.name.startswith(".")
    ]


def item(rel, fields):
    """One outline line: the note's title as a link, and its status."""
    title = fields.get("title") or Path(rel).stem
    title = title.replace("[", "\\[").replace("]", "\\]")
    status = fields.get("status")
    return f"- [{title}]({destination(rel)})" + (f" · {status}" if status else "")


def destination(rel):
    """A link destination markdown reads back as rel. A space or bracket would end or break a
    bare destination, so such a path goes in angle brackets, or is percent-encoded if it holds one."""
    if not set(rel) & set(" ()<>"):
        return rel
    if "<" in rel or ">" in rel:
        return quote(rel, safe="/")
    return f"<{rel}>"


def parent(fields, research):
    """The first research note in `related` that's in this folder, as a path relative to it."""
    for entry in flow_list(fields.get("related", "")):
        if entry.startswith("~/notes/") and entry[len("~/notes/") :] in research:
            return entry[len("~/notes/") :]
    return None


def build(root):
    """(index text, topics, notes, unfiled notes)."""
    research = dict(notes(root, "research"))
    others = [note for kind in KINDS[1:] for note in notes(root, kind)]
    every = {**research, **dict(others)}
    children, unfiled = defaultdict(list), []
    for rel, fields in others:
        if up := parent(fields, research):
            children[up].append((rel, fields))
        else:
            unfiled.append(rel)

    # area -> sub-area ("" for none) -> research notes
    tree = defaultdict(lambda: defaultdict(list))
    for rel, fields in research.items():
        topic = fields.get("topic", "")
        if TOPIC.fullmatch(topic):
            area, _, sub = topic.partition("/")
            tree[area][sub].append(rel)
        else:
            unfiled.append(rel)

    def branch(rels):
        """Each note's line, with the ideas and decisions that name it indented under it."""
        out = []
        for rel in sorted(rels):
            out.append(item(rel, every[rel]))
            out += ["  " + item(c, f) for c, f in sorted(children[rel])]
        return out

    lines = [HEADER]
    for area in sorted(tree):
        lines += [f"## {area}", ""]
        # Straight-under-area notes come first, or they'd sit under the last ### heading.
        if tree[area].get(""):
            lines += branch(tree[area][""]) + [""]
        for sub in sorted(s for s in tree[area] if s):
            lines += [f"### {sub}", ""] + branch(tree[area][sub]) + [""]
    lines += ["## Unfiled", ""]
    if unfiled:
        lines += branch(unfiled) + [""]

    topics = sum(len(subs) for subs in tree.values())
    return "\n".join(lines).rstrip("\n") + "\n", topics, len(every), len(unfiled)


def main():
    if len(sys.argv) != 2:
        print(USAGE, file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).expanduser()
    if not (root / "research").is_dir():
        print(f"{root} has no research/ folder", file=sys.stderr)
        return 1
    text, topics, count, unfiled = build(root)
    out = root / "index.md"
    out.write_text(text)
    print(f"{out}: {topics} topics, {count} notes, {unfiled} unfiled")
    return 0


if __name__ == "__main__":
    sys.exit(main())
